export const meta = '&audio&video&iframe'
export const iframe = '&meta=false&iframe'
export const screenshot = '&meta=false&screenshot&overlay.browser=dark'
export const pdf = '&meta=false&pdf'
export const insights = '&meta=false&insights'
