title: microlink | Extract information from a link
description: Microlink is a simple microservice for extract meta information from any link
image: /static/img/logo.png
twitter: '@windtodayco'
url: https://microlink.io
