const CARD_BASE_WIDTH = 500
const CARD_BASE_HEIGHT = 382
const CARD_RATIO_DESKTOP = 0.8
const CARD_RATIO_MOBILE = 1

export const CARD_HEIGHT_DESKTOP = `${CARD_BASE_HEIGHT * CARD_RATIO_DESKTOP}px`
export const CARD_WIDTH_DESKTOP = `${CARD_BASE_WIDTH * CARD_RATIO_DESKTOP}px`
export const CARD_WIDTH_MOBILE = `${338.6808 * CARD_RATIO_MOBILE}px`
export const CARD_HEIGHT_MOBILE = `${297.11 * CARD_RATIO_MOBILE}px`
