export const CARD_RATIO_DESKTOP = 1.3
export const CARD_RATIO_MOBILE = 1
export const CARD_HEIGHT_DESKTOP = `${223.2 * CARD_RATIO_DESKTOP}px`
export const CARD_WIDTH_DESKTOP = `${297.11 * CARD_RATIO_DESKTOP}px`
export const CARD_WIDTH_MOBILE = `${338.6808 * CARD_RATIO_MOBILE}px`
export const CARD_HEIGHT_MOBILE = `${297.11 * CARD_RATIO_MOBILE}px`
