export const CARD_RATIO_DESKTOP = 1.2
export const CARD_RATIO_MOBILE = 0.85
export const CARD_HEIGHT_DESKTOP = `${223.2 * CARD_RATIO_DESKTOP}px`
export const CARD_WIDTH_DESKTOP = `${338.6808 * CARD_RATIO_DESKTOP}px`
export const CARD_WIDTH_MOBILE = `${338.6808 * CARD_RATIO_MOBILE}px`
export const CARD_HEIGHT_MOBILE = `${338.6808 * CARD_RATIO_MOBILE}px`
